#
# toolchain setting
# 

MACRO(DS_ENABLE_ASM)
    #ENABLE_LANGUAGE(ASM-ATT)
	SET(CMAKE_ASM-ATT_ARCHIVE_APPEND ${CMAKE_C_ARCHIVE_APPEND})
	SET(CMAKE_ASM-ATT_ARCHIVE_CREATE ${CMAKE_C_ARCHIVE_CREATE})
	SET(CMAKE_ASM-ATT_ARCHIVE_FINISH ${CMAKE_C_ARCHIVE_FINISH})
	SET(CMAKE_ASM-ATT_COMPILER       ${CMAKE_C_COMPILER})
	#	SET(CMAKE_ASM-ATT_COMPILER_ABI   CMAKE_ASM-ATT_COMPILER_ABI
	#	SET(CMAKE_ASM-ATT_COMPILER_ID    CMAKE_ASM-ATT_COMPILER_ID
	SET(CMAKE_ASM-ATT_COMPILE_OBJECT ${CMAKE_C_COMPILE_OBJECT})
	SET(CMAKE_ASM-ATT_CREATE_SHARED_LIBRARY ${CMAKE_C_CREATE_SHARED_LIBRARY})
	SET(CMAKE_ASM-ATT_CREATE_SHARED_MODULE  ${CMAKE_C_CREATE_SHARED_MODULE})
	SET(CMAKE_ASM-ATT_CREATE_STATIC_LIBRARY ${CMAKE_C_CREATE_STATIC_LIBRARY})
	#	SET(CMAKE_ASM-ATT_FLAGS_DEBUG
	#	SET(CMAKE_ASM-ATT_FLAGS_MINSIZEREL
	#	SET(CMAKE_ASM-ATT_FLAGS_RELEASE
	#	SET(CMAKE_ASM-ATT_FLAGS_RELWITHDEBINFO
	#	SET(CMAKE_ASM-ATT_IGNORE_EXTENSIONS
	#	SET(CMAKE_ASM-ATT_LINKER_PREFERENCE
	SET(CMAKE_ASM-ATT_LINK_EXECUTABLE ${CMAKE_C_LINK_EXECUTABLE})
	#	SET(CMAKE_ASM-ATT_OUTPUT_EXTENSION
ENDMACRO (DS_ENABLE_ASM)

IF(DS_TARGET STREQUAL "X86")
	INCLUDE(X86)
	DS_SET_PLATFORM_X86()
ENDIF(DS_TARGET STREQUAL "X86")

IF(DS_TARGET STREQUAL "SMP865X")
	INCLUDE(Smp865x)
	DS_SET_PLATFORM_SMP865X()
ENDIF(DS_TARGET STREQUAL "SMP865X")

IF(DS_ENABLE_CCACHE)
    SET(CMAKE_C_COMPILER_ARG1 ${CMAKE_C_COMPILER})
	SET(CMAKE_C_COMPILER "ccache")
    SET(CMAKE_CXX_COMPILER_ARG1 ${CMAKE_CXX_COMPILER})
	SET(CMAKE_CXX_COMPILER "ccache")
    #SET(ENV{CCACHE_DIR} ${CMAKE_VA_WEBKIT_BINARY_DIR}/.ccache)
ENDIF(DS_ENABLE_CCACHE)

DS_ENABLE_ASM()


